# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zametka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=5000)),
                ('time_field', models.DateTimeField(default=None)),
            ],
        ),
    ]
